# Generated by Django 4.1.7 on 2023-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.TextField(db_column='api')),
                ('token', models.TextField(db_column='token')),
                ('params', models.TextField(db_column='request_params')),
                ('response', models.TextField(db_column='response')),
                ('method', models.TextField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_column='method')),
            ],
            options={
                'db_table': 'user_apis',
            },
        ),
    ]
